trigger:
  tags:
    include:
      - RC/*
  branches:
    include:
      - main
      
pool:
  vmImage: 'windows-latest'

variables:
- name: buildName
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/RC/')}}:
    value: ${{ replace(variables['Build.SourceBranchName'], 'RC/', '') }} 
  ${{ else }}:    
    value: _${{ variables['Build.SourceBranchName']}}

name: ${{ variables.buildName }}$(rev:.r)

resources:
  repositories:
    - repository: templates
      type: git
      name: Software Architecture/PipelineTemplates
      ref: refs/heads/main # specify the branch or tag

stages:
- template: Templates/Composite_Build.yml@templates  # Template reference
  parameters:
    isReleaseBuild: ${{ not(startsWith(variables.buildName, '_')) }}
    isSonarQubeScan: true
    sonarQubeOrganizationKey: "cbiz-appsdev"
    sonarQubeProjectKey: "CBIZ-AppsDev_CBIZ.CCH.BatchExtension"
    filesToSign:  "*.dll *.exe "
    buildProjects: "$(Build.SourcesDirectory)/**/CBIZ.CCH.BatchExtension.Presentation.*.csproj"
    versionNumber: "$(Build.BuildNumber)"
    
