using CBIZ.CCH.BatchExtension.Application.Features.GfrObjects;

namespace CBIZ.CCH.BatchExtension.Application.Features.GfrObjects;

public record FirmFlowReportResponse
(
    string ClientName,
    string ClientNumber,
    string DrawerId,
    string ServiceType,
    string EngagementType,
    string Workflow,
    string CurrentStep,
    string PIC,
    string AssignedTo,
    string AssignedOn,
    string Year,
    string PeriodEnd,
    string WorkflowDescription,
    string Progress,
    string Status,
    string Priority,
    string EFileYesOrNo,
    string ExtendedYesOrNo,
    string ReceivedOn,
    string CompletedOn,
    string SentOn,
    string Deliverables,
    string Responsible,
    string AssignmentHistory,
    string ReceivedFrom,
    string SentTo,
    string CompletedBy,
    string Accountable,
    string CurrentDueDate,
    string OriginalDueDate,
    string RoutingNotes,
    string PICYesOrNo,
    string AssignedToYesOrNo,
    string DateExtended,
    string DaysAtStep,
    string TotalDaysAtStep,
    string DaysBetweenRoutings,
    string TotalDaysInProcess,
    string FolderID,
    string FilingID,
    string LastUpdated,
    List<InformationField> InformationFields,
    List<RoutingSummary> RoutingSummary,
    List<ResponsibleUserOrGroup> ResponsibleUserOrGroups
);
